"use client";

import { useState, useEffect, use } from 'react';
import EstimatedPreview from '@/components/EstimatedPreview';
import QuotationPreview from '@/components/QuotationPreview';

export default function PublicSharePage({ params }: { params: Promise<{ publicId: string }> }) {
  // Use React.use() to unwrap params in Next.js 15+ if needed, or just await in useEffect.
  // params is a Promise in recent Next.js versions for Server Components, but this is a Client Component.
  // In Client Components, params is passed as a prop, but dealing with async params is safer.
  const resolvedParams = use(params) as { publicId: string };
  const publicId = resolvedParams.publicId;

  const [docData, setDocData] = useState<Record<string, unknown> | null>(null);
  const [docType, setDocType] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch(`/api/public/document/${publicId}`);
        if (!res.ok) {
            if (res.status === 404) throw new Error('Document not found');
            throw new Error('Failed to load document');
        }
        
        const responseData = await res.json();
        setDocData(responseData.data);
        setDocType(responseData.type);
        
        // set title
        const client = responseData.data?.receiver?.name || responseData.data?.receiver?.company || responseData.data?.clientName || 'Client';
        document.title = `${responseData.type} - ${client}`;

      } catch (err: unknown) {
        console.error(err);
        setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    };

    if (publicId) fetchData();
  }, [publicId]);

  // Responsive Scaling Logic
  const [scale, setScale] = useState(1);

  useEffect(() => {
    const handleResize = () => {
      // 210mm is approx 794px at 96 DPI, simplified to 800px base width for calculation
      const baseWidth = 800; // The width of the A4 container
      const windowWidth = window.innerWidth;
      
      if (windowWidth < baseWidth) {
          // Add some padding (20px)
          const newScale = (windowWidth - 20) / baseWidth;
          setScale(newScale);
      } else {
          setScale(1);
      }
    };

    handleResize(); // Initial calculation
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  if (loading) return (
      <div className="flex items-center justify-center min-h-screen bg-slate-50">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
  );

  if (error) return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-slate-50 gap-4">
          <div className="text-red-500 text-xl font-bold">😕 Oops!</div>
          <div className="text-slate-600">{error}</div>
      </div>
  );

  if (!docData) return null;

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col items-center py-4 md:py-8 overflow-x-hidden">
       {/* Public Header */}
       <div className="mb-4 md:mb-6 no-print w-full max-w-[800px] flex flex-col md:flex-row justify-between items-center px-4 gap-4 md:gap-0">
          <div className="text-sm text-slate-500 text-center md:text-left">
              Shared {docType}
              <div className="text-xs text-slate-400">View below or download PDF</div>
          </div>
          <button 
            onClick={() => window.print()} 
            className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow hover:bg-blue-700 transition flex items-center gap-2 font-medium text-sm md:text-base w-full md:w-auto justify-center"
          >
            <span>🖨️</span> Print / Save PDF
          </button>
       </div>

       {/* Scaled Preview Container */}
       <div 
          className="shadow-2xl bg-white origin-top transition-transform duration-200 print-container"
          style={{ 
              transform: `scale(${scale})`,
              marginBottom: `-${(1 - scale) * 1123}px` // Compensate for vertical space lost by scaling (approx A4 height)
          }}
       >
          {docType === 'Estimate' ? (
              <EstimatedPreview data={docData as Parameters<typeof EstimatedPreview>[0]['data']} showGst={(docData?.showGst as boolean) ?? false} />
          ) : (
              <QuotationPreview data={docData} />
          )}
       </div>

       <div className="mt-8 text-slate-400 text-xs text-center no-print w-full px-4">
           Generated by Champion Security Services
           <br/>
           <span className="opacity-50">Best viewed on Desktop or Printed</span>
       </div>

       <style>{`
          @media print {
            .no-print { display: none !important; }
            body { background: white; }
            /* Reset scaling for print */
            .print-container {
                transform: none !important;
                margin-bottom: 0 !important;
                box-shadow: none !important;
            }
          }
       `}</style>
    </div>
  );
}
